export GOVC_URL=...
export GOVC_USERNAME=...
export GOVC_PASSWORD=...
export GOVC_INSECURE=true
export GOVC_CLUSTER=...
export GOVC_DATACENTER=...
export GOVC_DATASTORE=...
export GOVC_NETWORK=Openshift

export IP_GATEWAY=...
export IP_DNS=...

export INSTALLER=openshift-install-4.12-vsphere
