kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bootstrap-operators
rules:
  - verbs:
      - get
      - update
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/approval
  - verbs:
      - approve
    apiGroups:
      - certificates.k8s.io
    resources:
      - signers
  - verbs:
      - create 
    apiGroups:
      - config.openshift.io 
    resources:
      - oauths
  - verbs:
      - get
      - update 
      - patch
    apiGroups:
      - config.openshift.io 
    resources:
      - oauths
    resourceNames:
      - cluster 

