apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bootstrap-operators
  namespace: openshift-operator-lifecycle-manager
rules:
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - update
      - delete
      - patch
    resourceNames:
      - bootstrap-operators
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - update
      - delete
      - patch
    resourceNames:
      - bootstrap-operators-script
@operators@
