kind: Secret
apiVersion: v1
metadata:
  name: htpasswd
  namespace: openshift-config
data:
  htpasswd: >-
    aHBlX3JlZGhhdDokYXByMSRzNGg0QVlORyROOWZYbHdVTGtOeW5iRThNNmw5czkvCnJlYWRvbmx5OiQyeSQwNSRqZ09HMjBqL3BEVlFCT0VBTFF1STVPWDNkOVpleS5HLk9JQUdMUXhGbGtwdjczbXRHWEdPVwo=
type: Opaque
