kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bootstrap-operators
  namespace: openshift-operator-lifecycle-manager
subjects:
  - kind: User 
    apiGroup: rbac.authorization.k8s.io
    name: 'system:node:master-0-@cluster@'
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:node:master-1-@cluster@'
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:node:master-2-@cluster@'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bootstrap-operators
